 CREATE Table VIDEO_INFO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    VIDEO_NAME TEXT NOT NULL,
    CONFIG TEXT,
    DURATION REAL NOT NULL,
    BITRATE INT NOT NULL,
    CODEC TEXT,
    CODEC_PROFILE TEXT,
    COLOR_ENCODING TEXT,
    WIDTH INT,
    HEIGHT INT,
    SAR TEXT,
    DAR TEXT,
    FPS INT); 

CREATE TABLE RUN_INFO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SOURCE INTEGER NOT NULL,
    DEST   INTEGER NOT NULL,
    REAL_T REAL NOT NULL,
    USER_T REAL,
    SYSTEM_T REAL,
    FOREIGN KEY (SOURCE) REFERENCES video_info (ID),
    FOREIGN KEY (DEST) REFERENCES video_info (ID)
);
